# Generated by Django 5.2.6 on 2025-10-16 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotionPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sequence_data', models.JSONField(help_text='Array of joint states and timestamps')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(default='Generic Arm', max_length=50)),
                ('port', models.CharField(blank=True, help_text='USB or serial port identifier', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(help_text='Filesystem path to the dataset file or directory', max_length=1024)),
                ('source_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='control.motionpattern')),
            ],
        ),
        migrations.AddField(
            model_name='motionpattern',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_patterns', to='control.robot'),
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_arm_serial', models.CharField(blank=True, max_length=100)),
                ('follower_arm_serial', models.CharField(blank=True, max_length=100)),
                ('calibration_data', models.JSONField(help_text='Stores detailed calibration parameters')),
                ('calibrated_at', models.DateTimeField(auto_now_add=True)),
                ('robot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calibration', to='control.robot')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('hyperparameters', models.JSONField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('model_path', models.CharField(blank=True, help_text='Path to the final trained model file', max_length=1024)),
                ('training_log', models.TextField(blank=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_runs', to='control.dataset')),
            ],
        ),
    ]
